# Save Model Using Joblib and Pickle

### The following code is from the first tutorial for linear regression

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [9]:
model.predict([[5000]])

array([859554.79452055])

## Start of this tutorial
### pickle

In [10]:
import pickle

In [13]:
# open a file and write binary to it
with open('model_pickle', 'wb') as f:
    # dump the model to the create file, Jupyter Notebook cannot open this file
    pickle.dump(model, f)

In [16]:
# open a file with read binary mode
with open('model_pickle', 'rb') as f:
    # use load() to get the model
    model_pickle = pickle.load(f)

model_pickle.predict([[5000]])  # the prediction is same as the previous prediction

array([859554.79452055])

### joblib

In [18]:
import joblib

In [20]:
# you do not need to open a file to use joblib
# joblib.dump(model, 'file_name')
joblib.dump(model, 'model_joblib')

['model_joblib']

In [23]:
model_joblib = joblib.load('model_joblib')

In [24]:
model_joblib.predict([[5000]])

array([859554.79452055])

### These two libraries have the same function but joblib is better to use because it is more efficient on object that carry large numpy arrays