# Basics for numpy

### Create numpy array

In [1]:
import numpy as np
a = np.array([5, 6, 9])  # np.array can be used to create array
# the array can be accessed just like a list
print(a[0])
print(a[2])

5
9


In [19]:
a = np.array([[1, 2], [3, 4], [5, 6]])  # can be also used to create a 2d array
print(a.ndim)  # used to print the dimension
print(a.itemsize)  # used to print the byte size of each of the element in the array
print(a.dtype)  # get the data type

2
8
int64


### Different numpy functions

In [16]:
# to change the data type, specify the type when creating the array. Can be complex number if dtype=complex
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.int32)
a.itemsize

4

In [17]:
print(a.size)  # print the total number of elements in the array
print(a.shape)  # print the dimension of the array

6
(3, 2)


In [20]:
print(np.zeros((3, 4)))  # to get an array filled with zeros, give the shape of the array
print(np.ones((2, 5)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
print(np.arange(0, 5))  # similar to range(0, 5), creates an array with numbers 0 - 4
print(np.arange(0, 5, 2))

[0 1 2 3 4]
[0 2 4]


In [22]:
print(np.linspace(1, 5, 10))  # creates an array that has 10 number linearly spaced (equal difference)
print(np.linspace(1, 5, 5))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1. 2. 3. 4. 5.]


In [24]:
# these functions below will not alter the orinigal array, they returns a new array
print(a.shape)
print(a.reshape(2, 3))  # it reshape the original array, but the shape must be compactable 
print(a.reshape(1, 6))
print(a.ravel())  # this function flatten the array and make it one dimensional

(3, 2)
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


### Mathmatical functions and operations with numpy.array

In [27]:
# numpy also provides some simple function like max() min() and sum()
a = np.array([[1, 2, 3],
              [3, 4, 5],
              [4, 5, 6]])
print(a.min())
print(a.max())
print(a.sum())
# the rows are axis 1 and coloumns are axis 0
print(a.sum(axis=0))
print(a.sum(axis=1))

1
6
33
[ 8 11 14]
[ 6 12 15]


In [31]:
# numpy provides std() and sqrt() functions
print(np.sqrt(2))
print(np.std(np.array([[1, 2, 3], [4, 5, 6]])))
print(np.std(np.array([1, 2, 3, 4, 5, 6])))

1.4142135623730951
1.707825127659933
1.707825127659933


In [33]:
# numpy provides basic computation between two arrays
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a.dot(b))  # the dot product

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
